---
namespace: lit
name: rhel
version: 1.2.0
readme: README.md
description: >-
  RHEL-focused collection for OS baseline, hardening, user/package management,
  and day-2 operational tasks.
repository: https://github.com/lightning-it/ansible-collection-rhel
authors:
  - Lightning IT
license:
  - GPL-2.0-only
tags:
  - rhel
  - linux
  - hardening
  - baseline
  - security
  - compliance
  - automation
dependencies:
  ansible.posix: "*"
  community.general: "*"
build_ignore:
  - node_modules
  - vagrant
  - .git
  - .github
  - .gitignore
  - .molecule
  - ansible_collections
  - infra
  - "*.terraform*"
  - "*.tar.gz"
