namespace: lit
name: rhel
version: 1.1.1
readme: README.md
description: 'RHEL-focused Ansible collection for ModuLix, providing OS baseline,
  hardening, user and package management, and day-2 operational tasks for Red Hat
  Enterprise Linux systems.

  '
repository: https://github.com/lightning-it/ansible-collection-rhel
authors:
- Lightning IT
license:
- GPL-2.0-only
tags:
- rhel
- linux
- hardening
- baseline
- security
- compliance
- automation
dependencies:
  ansible.posix: '*'
build_ignore:
- node_modules
- vagrant
- .git
- .github
- .gitignore
- .molecule
- ansible_collections
- infra
- '*.terraform*'
- '*.tar.gz'
