---
- name: Converge rhel.baseline
  hosts: rhel-baseline
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    baseline_packages_present:
      - curl
      - vim
      - jq
    baseline_timezone: Europe/Berlin
    baseline_locale: en_US.UTF-8
    baseline_chrony_pools:
      - "pool.ntp.org iburst"
    baseline_sysctl:
      net.ipv4.ip_forward: 0
  pre_tasks:
    - name: Ensure python3 is present
      ansible.builtin.raw: |
        if ! command -v python3 >/dev/null 2>&1; then
          dnf -y install python3
        fi
      changed_when: false

  roles:
    - role: lit.rhel.baseline
