---
driver:
  name: docker

platforms:
  - name: rhel_sshd
    image: quay.io/rockylinux/rockylinux:9
    pre_build_image: true

provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          rhel_sshd:
            ansible_connection: docker
  playbooks:
    converge: converge.yml
    verify: verify.yml

verifier:
  name: ansible
