---
driver:
  name: docker

platforms:
  - name: firewalld_instance
    image: quay.io/rockylinux/rockylinux:9
    pre_build_image: true
    privileged: true

provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          firewalld_instance:
            ansible_connection: docker
  playbooks:
    converge: converge.yml
    verify: verify.yml

verifier:
  name: ansible
