---
- name: Verify firewalld configuration
  hosts: firewalld_instance
  gather_facts: false
  become: false

  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Assert firewalld package is present
      ansible.builtin.assert:
        that:
          - "'firewalld' in ansible_facts.packages"
        fail_msg: "firewalld package is not installed"
