---
driver:
  name: docker

dependency:
  name: galaxy
  options:
    requirements-file: "${MOLECULE_PROJECT_DIRECTORY}/collections/requirements.yml"
platforms:
  - name: control
    image: quay.io/rockylinux/rockylinux:9
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          control:
            ansible_connection: docker
verifier:
  name: ansible
