---
driver:
  name: docker

dependency:
  name: galaxy
  options:
    requirements-file: "${MOLECULE_PROJECT_DIRECTORY}/collections/requirements.yml"

platforms:
  - name: hostname_instance
    image: quay.io/rockylinux/rockylinux:9
    pre_build_image: true

provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          hostname_instance:
            ansible_connection: docker
  playbooks:
    converge: converge.yml
    verify: verify.yml

verifier:
  name: ansible
