---
driver:
  name: default

dependency:
  name: galaxy
  options:
    requirements-file: "${MOLECULE_PROJECT_DIRECTORY}/collections/requirements.yml"
platforms:
  - name: rhsm_instance

provisioner:
  name: ansible
  playbooks:
    create: ../incus_shared/create.yml
    converge: converge.yml
    verify: verify.yml
    destroy: ../incus_shared/destroy.yml

verifier:
  name: ansible
