---
- name: Verify firefox config syntax coverage
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read lit.rhel.firefox_config coverage marker
      ansible.builtin.slurp:
        src: /tmp/lit-rhel-firefox_config-molecule-coverage
      register: firefox_config_molecule_coverage_marker

    - name: Assert lit.rhel.firefox_config coverage stub ran
      ansible.builtin.assert:
        that:
          - (firefox_config_molecule_coverage_marker.content | b64decode | trim) == "syntax_stub"
        quiet: true
