---
galaxy_info:
  role_name: rhsm
  namespace: lit
  author: Lightning IT
  description: Register or unregister RHEL systems with RHSM or Satellite.
  company: Lightning IT
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions: ["9", "10"]
  galaxy_tags:
    - rhel
    - rhsm
    - satellite
    - subscription
dependencies: []
