---
- name: Verify vscode deploy syntax coverage
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Read lit.rhel.vscode_deploy coverage marker
      ansible.builtin.slurp:
        src: /tmp/lit-rhel-vscode_deploy-molecule-coverage
      register: vscode_deploy_molecule_coverage_marker

    - name: Assert lit.rhel.vscode_deploy coverage stub ran
      ansible.builtin.assert:
        that:
          - (vscode_deploy_molecule_coverage_marker.content | b64decode | trim) == "syntax_stub"
        quiet: true
