---
- name: Converge SELinux role on RHEL 9 (Vagrant)
  hosts: rhel_selinux_hosts
  become: true
  vars:
    ansible_host: "{{ lookup('env', 'VAGRANT_SSH_HOST') | default('host.docker.internal', true) }}"
    ansible_user: "{{ lookup('env', 'VAGRANT_SSH_USER') | default('vagrant', true) }}"
    ansible_port: "{{ lookup('env', 'VAGRANT_SSH_PORT') | default('55222', true) }}"
    ansible_ssh_private_key_file: "/workspace/vagrant/rhel9/.vagrant/machines/default/qemu/private_key"
    ansible_ssh_common_args: >-
      -o StrictHostKeyChecking=no
      -o UserKnownHostsFile=/dev/null
      -o ControlMaster=no
      -o ControlPath=none
      -o ControlPersist=no

  roles:
    - role: lit.rhel.selinux
      vars:
        selinux_state: enforcing
        selinux_policy: targeted
