---
- name: Converge SELinux role on RHEL-compatible Incus target
  hosts: all
  become: true

  roles:
    - role: lit.rhel.selinux
      vars:
        selinux_state: enforcing
        selinux_policy: targeted
