---
dependency:
  name: galaxy

driver:
  name: default

platforms:
  - name: chrony_rhel9_target
    groups:
      - chrony_hosts

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml
  inventory:
    host_vars:
      chrony_rhel9_target:
        ansible_host: >-
          {{ lookup('env', 'VAGRANT_SSH_HOST')
             | default('host.docker.internal', true) }}
        ansible_port: >-
          {{ lookup('env', 'VAGRANT_SSH_PORT') | default('55222', true) }}
        ansible_user: >-
          {{ lookup('env', 'VAGRANT_SSH_USER') | default('vagrant', true) }}
        ansible_ssh_private_key_file: >-
          /workspace/vagrant/rhel9/.vagrant/machines/default/qemu/private_key
        ansible_ssh_common_args: >-
          -o StrictHostKeyChecking=no
          -o UserKnownHostsFile=/dev/null
          -o ControlMaster=no
          -o ControlPath=none
          -o ControlPersist=no

verifier:
  name: ansible
