---
- name: Prechecks
  ansible.builtin.import_tasks: assert.yml
  tags: always

- name: End host when xrdp role is disabled
  ansible.builtin.meta: end_host
  when: not (xrdp_enabled | bool)

- name: Load RHEL-version-specific xrdp variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"

- name: Install xrdp packages
  ansible.builtin.import_tasks: install.yml

- name: Configure xrdp
  ansible.builtin.import_tasks: configure.yml
  when: xrdp_config_manage | bool

- name: Configure SELinux for xrdp
  ansible.builtin.import_tasks: selinux.yml
  when: xrdp_selinux_manage | bool

- name: Configure firewalld for xrdp
  ansible.builtin.import_tasks: firewall.yml
  when: xrdp_firewalld_manage | bool

- name: Manage xrdp services
  ansible.builtin.import_tasks: service.yml
  when: xrdp_service_manage | bool
