---
galaxy_info:
  author: Lightning IT
  description: Remove Visual Studio Code managed state on RHEL 9.
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: EL
      versions:
        - "9"
dependencies: []
